Enable publishing all ants' HTTP API ports
NebulousLabs/docker-sia-ant-farm pull request #10
Opened 2020-11-18 17:18 UTC by firyx

This PR enables to publish any (or all) HTTP API ant ports outside of docker container and adds a test to check publishing port forwarding of two ports set in custom configuration.

2020-11-18 17:33 UTC, MSevey requested changes

2020-11-18 17:33 UTC, MSevey commented on README.md
> +### v1.0.4.1
make v1.0.5 so we keep it sematic.

2020-11-18 17:33 UTC, MSevey commented on README.md
> +* Sia Ant Farm `v1.0.4` based on Sia `v.1.5.3`
remove this line, just say what is new with v1.0.5

2020-11-18 17:33 UTC, MSevey commented on README.md
> +            "APIAddr": "127.0.0.1:10980",
formatting, indent

2020-11-19 13:00 UTC, ro-tex approved these changes
LGTM.

2020-11-19 13:00 UTC, ro-tex commented on build-test.sh
> +  timeout 120 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:9988/consensus"; do sleep 1; done' && timeout 10 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:10988/consensus"
Personal preference, but I'd move this to a function. It's long enough to make me scratch my head for a while.

2020-11-19 13:00 UTC, ro-tex commented on run.sh
> +internal_ip_address=$(hostname -I)
Oh, this is nice!

2020-11-19 15:10 UTC, MSevey commented on build-test.sh
> +  timeout 120 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:9988/consensus"; do sleep 1; done' && timeout 10 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:10988/consensus"
@firyx is that an easy change? Or at least make it a multi line statement for readability.

2020-11-19 17:52 UTC, firyx commented on build-test.sh
> +  timeout 120 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:9988/consensus"; do sleep 1; done' && timeout 10 bash -c 'until curl -A "Sia-Agent" --fail "http://localhost:10988/consensus"
Extracted to a function for better readability and higher reuse.

2020-11-20 07:10 UTC, merged